### ISSUE TITLE
Odds and Ends list

### ISSUE THREAD

**Issue by NickRoss** [dsi-clinic/the-clinic#23]
Add the final technical submission to canvas (as an upload submission in the final week).

Require the progress and planning docs to be PDFs (and then update the rubric / template to note this)

Add the email requirement (as a non-upload?) graded assignment.

Read through docs a few times and identify more holes / issues. I'm sure that there are a few.

**Comment by timhannifan** [comment]
Add the final technical submission to canvas (as an upload submission in the final week). [DONE]
Add the email requirement (as a non-upload?) graded assignment. [DONE]
Require the progress and planning docs to be PDFs (and then update the rubric / template to note this) [DONE]
